/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-application-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":utilities"))
}

tasks.register("task1"){
    dependsOn(tasks.classes)
    group = "Custom"
    description = "A custom task"
}

tasks.named("task1"){  
    doFirst {
        println("NAMED TASK1 - doFirst: This is executed during the execution phase")
    }
    doLast {
        println("NAMED TASK1 - doLast: This is executed during the execution phase")
    }
}

application {
    // Define the main class for the application.
    mainClass = "org.example.app.App"
}
